import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import StyleDictionary from 'style-dictionary';

type TokenNode = { $value?: unknown; $type?: string; $description?: string; [key: string]: unknown };

const ROOT = process.cwd();
const TOKEN_DIRS = ['tokens/primitive', 'tokens/semantic', 'tokens/component'];
const BUILD = join(ROOT, 'build');

function loadTree(): TokenNode {
	const tree: TokenNode = {};
	for (const dir of TOKEN_DIRS) {
		for (const file of readdirSync(join(ROOT, dir)).filter((f) => f.endsWith('.json'))) {
			deepMerge(tree, JSON.parse(readFileSync(join(ROOT, dir, file), 'utf8')));
		}
	}
	return tree;
}

function deepMerge(target: TokenNode, source: TokenNode) {
	for (const [key, value] of Object.entries(source)) {
		if (value && typeof value === 'object' && !Array.isArray(value) && !('$value' in (value as TokenNode))) {
			target[key] = target[key] ?? {};
			deepMerge(target[key] as TokenNode, value as TokenNode);
		} else {
			target[key] = value;
		}
	}
}

function lookup(tree: TokenNode, path: string): TokenNode {
	const node = path.split('.').reduce<unknown>((acc, part) => (acc as TokenNode)?.[part], tree) as TokenNode | undefined;
	if (!node || !('$value' in node)) throw new Error(`Unknown token reference {${path}}`);
	return node;
}

export function resolveValue(tree: TokenNode, value: unknown, seen: string[] = []): unknown {
	if (typeof value === 'string') {
		const whole = value.match(/^\{([^}]+)\}$/);
		if (whole) {
			if (seen.includes(whole[1])) throw new Error(`Circular reference ${[...seen, whole[1]].join(' -> ')}`);
			return resolveValue(tree, lookup(tree, whole[1]).$value, [...seen, whole[1]]);
		}
		return value;
	}
	if (value && typeof value === 'object' && !Array.isArray(value)) {
		return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, resolveValue(tree, v, seen)]));
	}
	return value;
}

function luminance(hex: string) {
	const channels = hex.replace('#', '').match(/../g)!.map((h) => parseInt(h, 16) / 255);
	const [r, g, b] = channels.map((c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4));
	return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

export function contrastRatio(a: string, b: string) {
	const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
	return (hi + 0.05) / (lo + 0.05);
}

function walk(node: TokenNode, path: string[], visit: (path: string[], token: TokenNode) => void) {
	if ('$value' in node) return visit(path, node);
	for (const [key, child] of Object.entries(node)) {
		if (!key.startsWith('$') && child && typeof child === 'object') walk(child as TokenNode, [...path, key], visit);
	}
}

const tree = loadTree();
mkdirSync(BUILD, { recursive: true });

const pairs: { fg: string; bg: string; min: number; use: string; note?: string }[] = JSON.parse(readFileSync(join(ROOT, 'tokens/contrast-pairs.json'), 'utf8')).pairs;
const rows = pairs.map((pair) => {
	const fg = resolveValue(tree, `{color.${pair.fg}}`) as string;
	const bg = resolveValue(tree, `{color.${pair.bg}}`) as string;
	const ratio = contrastRatio(fg, bg);
	return { ...pair, fgHex: fg, bgHex: bg, ratio, pass: ratio >= pair.min };
});
const failures = rows.filter((row) => !row.pass);
writeFileSync(
	join(BUILD, 'contrast-report.md'),
	[
		'# Contrast report',
		'',
		'Generated by `npm run tokens` from `tokens/contrast-pairs.json`. Normal text needs 4.5:1, large text and UI parts 3:1 (WCAG AA).',
		'',
		'| Foreground | Background | Use | Hex | Ratio | Required | Result |',
		'|---|---|---|---|---|---|---|',
		...rows.map((r) => `| \`${r.fg}\` | \`${r.bg}\` | ${(r as any).use}${(r as any).note ? ` (${(r as any).note})` : ""} | ${r.fgHex} on ${r.bgHex} | ${r.ratio.toFixed(2)}:1 | ${r.min}:1 | ${r.pass ? 'pass' : 'FAIL'} |`),
		'',
		`${rows.length} pairs, ${failures.length} failures.`,
		'',
	].join('\n'),
);

const cssName = (path: string[]) => `--ds-${path.join('-')}`;
const TAILWIND_COLOR_ALIASES: Record<string, string> = {
	'color.bg.default': 'surface',
	'color.bg.subtle': 'surface-subtle',
	'color.bg.inverse': 'surface-inverse',
	'color.bg.tint': 'tint',
	'color.bg.brand': 'brand',
	'color.text.default': 'fg',
	'color.text.muted': 'fg-muted',
	'color.text.subtle': 'fg-subtle',
	'color.text.inverse': 'fg-inverse',
	'color.text.on-brand': 'on-brand',
	'color.border.default': 'line',
	'color.border.subtle': 'line-subtle',
	'color.border.strong': 'line-strong',
	'color.action.primary': 'action',
	'color.action.primary-hover': 'action-hover',
	'color.action.primary-fg': 'on-action',
	'color.status.success': 'success',
	'color.status.warning': 'warning',
	'color.status.danger': 'danger',
	'color.focus.ring': 'focus',
};

const cssLines: string[] = [];
const themeColor: string[] = [];
walk(tree, [], (path, token) => {
	const key = path.join('.');
	const value = resolveValue(tree, token.$value);
	if (token.$type === 'color') {
		cssLines.push(`\t${cssName(path)}: ${value};`);
		if (path[1] && ['black', 'white', 'blue', 'navy', 'neutral'].includes(path[1]) && path.length > 2 || ['black', 'white'].includes(path[1])) {
			themeColor.push(`\t--color-${path.slice(1).join('-')}: var(${cssName(path)});`);
		}
		if (TAILWIND_COLOR_ALIASES[key]) themeColor.push(`\t--color-${TAILWIND_COLOR_ALIASES[key]}: var(${cssName(path)});`);
	}
});

const space = tree.space as TokenNode;
const radius = tree.radius as TokenNode;
const duration = tree.duration as TokenNode;
const easing = tree.easing as TokenNode;
const text = tree.text as TokenNode;
const fontFamily = (tree.font as TokenNode).family as TokenNode;
const fontWeight = (tree.font as TokenNode).weight as TokenNode;

const rem = (px: string) => `${parseFloat(px) / 16}rem`;
const families = Object.fromEntries(
	Object.entries(fontFamily).filter(([k]) => !k.startsWith('$')).map(([k, v]) => [k, ((v as TokenNode).$value as string[]).map((f) => (f.includes(' ') && !f.startsWith('var(') ? `"${f}"` : f)).join(', ')]),
);
const bezier = (v: unknown) => `cubic-bezier(${(v as number[]).join(', ')})`;

for (const [k, v] of Object.entries((tree.layout as TokenNode) ?? {})) if (!k.startsWith('$')) cssLines.push(`\t--ds-layout-${k}: ${(v as TokenNode).$value};`);
for (const [k, v] of Object.entries(space)) if (!k.startsWith('$')) cssLines.push(`\t--ds-space-${k}: ${(v as TokenNode).$value};`);
for (const [k, v] of Object.entries(radius)) if (!k.startsWith('$')) cssLines.push(`\t--ds-radius-${k}: ${(v as TokenNode).$value};`);
for (const [k, v] of Object.entries(duration)) if (!k.startsWith('$')) cssLines.push(`\t--ds-duration-${k}: ${(v as TokenNode).$value};`);
for (const [k, v] of Object.entries(easing)) if (!k.startsWith('$')) cssLines.push(`\t--ds-easing-${k}: ${bezier((v as TokenNode).$value)};`);
for (const [k, v] of Object.entries(families)) cssLines.push(`\t--ds-font-${k}: ${v};`);
for (const [k, v] of Object.entries(fontWeight)) if (!k.startsWith('$')) cssLines.push(`\t--ds-font-weight-${k}: ${(v as TokenNode).$value};`);

const version = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).version;
const header = `/* Generated by context-ds ${version} from tokens/. Do not edit. */`;
writeFileSync(join(BUILD, 'tokens.css'), `${header}\n:root {\n${cssLines.join('\n')}\n}\n`);

const textLines: string[] = [];
for (const [name, token] of Object.entries(text)) {
	if (name.startsWith('$')) continue;
	const t = resolveValue(tree, (token as TokenNode).$value) as { fontSize: string; lineHeight: number; fontWeight: number; fontFamily: string[] };
	textLines.push(`\t--text-${name}: ${rem(t.fontSize)};`, `\t--text-${name}--line-height: ${t.lineHeight};`, `\t--text-${name}--font-weight: ${t.fontWeight};`, `\t--text-${name}--letter-spacing: 0;`);
}

const theme = `${header}
@import "./tokens.css";

@theme inline {
\t--color-*: initial;
${themeColor.join('\n')}

\t--font-*: initial;
${Object.keys(families).map((k) => `\t--font-${k}: var(--ds-font-${k});`).join('\n')}

\t--font-weight-*: initial;
${Object.entries(fontWeight).filter(([k]) => !k.startsWith('$')).map(([k, v]) => `\t--font-weight-${k}: ${(v as TokenNode).$value};`).join('\n')}

\t--text-*: initial;
${textLines.join('\n')}

\t--radius-*: initial;
${Object.keys(radius).filter((k) => !k.startsWith('$') && k !== 'none').map((k) => `\t--radius-${k}: var(--ds-radius-${k});`).join('\n')}

\t--ease-*: initial;
${Object.keys(easing).filter((k) => !k.startsWith('$') && k !== 'linear').map((k) => `\t--ease-${k}: var(--ds-easing-${k});`).join('\n')}
}
`;
writeFileSync(join(BUILD, 'theme.css'), theme);
writeFileSync(join(BUILD, 'theme.scoped.css'), theme.replace(/^\t--[a-z-]+-\*: initial;\n/gm, '').replace('@theme inline {', '/* Scoped: adds Context.dev utilities without removing the app\'s own theme. */\n@theme inline {'));

const preset = `${header.replace('/*', '//').replace(' */', '')}
// Tailwind v3 preset. Tailwind v4 projects import build/theme.css instead.
const preset = {
\ttheme: {
\t\tcolors: {
\t\t\ttransparent: 'transparent',
\t\t\tcurrent: 'currentColor',
${themeColor.map((line) => { const [, name, v] = line.match(/--color-([^:]+): (.+);/)!; return `\t\t\t'${name}': '${v}',`; }).join('\n')}
\t\t},
\t\tfontFamily: {
${Object.keys(families).map((k) => `\t\t\t${k}: ['var(--ds-font-${k})'],`).join('\n')}
\t\t},
\t\tborderRadius: {
\t\t\tnone: '0px',
${Object.keys(radius).filter((k) => !k.startsWith('$') && k !== 'none').map((k) => `\t\t\t${k}: 'var(--ds-radius-${k})',`).join('\n')}
\t\t\tfull: '9999px',
\t\t},
\t\textend: {},
\t},
};

export default preset;
`;
writeFileSync(join(BUILD, 'tailwind.preset.ts'), preset);

const colorNames = [...new Set(themeColor.map((line) => line.match(/--color-([^:]+):/)![1]))];
const textNames = Object.keys(text).filter((k) => !k.startsWith('$'));
const radiusNames = Object.keys(radius).filter((k) => !k.startsWith('$') && k !== 'none');
const easeNames = Object.keys(easing).filter((k) => !k.startsWith('$') && k !== 'linear');
const weightNames = Object.keys(fontWeight).filter((k) => !k.startsWith('$'));
writeFileSync(
	join(ROOT, 'registry', 'ui', 'cx', 'cx.ts'),
	`import { extendTailwindMerge } from 'tailwind-merge';

// Generated by npm run tokens. Teaches tailwind-merge the brand token names, so a class passed in overrides the default it conflicts with.
const merge = extendTailwindMerge({
	extend: {
		theme: {
			color: ${JSON.stringify(colorNames)},
			text: ${JSON.stringify(textNames)},
			radius: ${JSON.stringify(radiusNames)},
			ease: ${JSON.stringify(easeNames)},
			'font-weight': ${JSON.stringify(weightNames)},
		},
	},
});

export function cx(...parts: Array<string | false | null | undefined>) {
	return merge(parts.filter(Boolean).join(' '));
}
`,
);

const sd = new StyleDictionary({
	source: TOKEN_DIRS.map((d) => `${d}/**/*.json`),
	usesDtcg: true,
	log: { verbosity: 'silent', warnings: 'disabled' },
	platforms: { json: { transformGroup: 'js', buildPath: 'build/', files: [{ destination: 'tokens.flat.json', format: 'json/flat' }] } },
});
await sd.buildAllPlatforms();

console.log(`tokens: ${rows.length} contrast pairs, ${failures.length} failures. Wrote build/tokens.css, build/theme.css, build/tailwind.preset.ts, build/tokens.flat.json, build/contrast-report.md`);
if (failures.length) {
	for (const f of failures) console.error(`contrast FAIL ${f.fg} on ${f.bg}: ${f.ratio.toFixed(2)}:1, needs ${f.min}:1`);
	process.exit(1);
}
